# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [ push, pull_request ] # когда срабатывает (на push, pull_request)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      #    - name: Run java app
      #      run: java -jar ${{ github.workspace }}/artifacts/app-order.jar &
      #    - name: Grant execute permission for gradlew
      #      run: chmod +x gradlew
      #    - name: Build with Gradle
      #      run: ./gradlew build

      - name: Build and run tests
      run: |
        java -jar ${{ github.workspace }}/artifacts/app-order.jar &
        echo "Sleeping for 10"
        sleep 50
        chmod +x gradlew
        ./gradlew test --info -Dselenide.headless=true
